### ISSUE TITLE
More special characters needs to be filtered out for a better security 

### ISSUE THREAD

**Issue by danishtariqq** [zvory/csv-safe#7]
@zvory First of all, you have done an amazing job with this gem. 

It is suggested to filter out more special characters such as **|** and  **%**

Because the current gem could be bypassed with the use of such vector - **%0A-3+3+cmd|' /C calc'!D2** in older versions. 

### References:- 
https://hackerone.com/reports/223999
https://github.com/WeblateOrg/weblate/commit/d9e136ff228e3760fd6dd7572869ac38e9a81809
https://bugzilla.mozilla.org/show_bug.cgi?id=1259881

**Comment by zvory** [comment]
Thank you.

**Comment by danishtariqq** [comment]
https://github.com/zvory/csv-safe/pull/8

**Comment by danishtariqq** [comment]
@zvory Can we claim [CVE ](https://cve.mitre.org/)for this? i.e. Older version was not secured properly to filtrate enough characters against CSV Injection so was not fully securing and thus could be a cause of vulnerability in applications using older versions of csv-safe gem.

 Steps needs to be done could be simply putting it in the Security advisory of your repository and adding details on why the newer version was created.

**Comment by zvory** [comment]
@danishtariqq Could you put up a PR?

**Comment by danishtariqq** [comment]
> @danishtariqq Could you put up a PR?

https://github.com/zvory/csv-safe/pull/8 @zvory

**Comment by zvory** [comment]
@danishtariqq Oh sorry I meant for the CVE. I assumed that went into the repo. If it doesn't, feel free to make one! Sounds like a good idea.

**Comment by danishtariqq** [comment]
@zvory - https://github.com/zvory/csv-safe/pull/9
